# .github/workflows/run-script.yml
name: Run script

on:
  workflow_dispatch:
    inputs:
      MESSAGE:
        description: "Mensaje a enviar"
        required: false
        default: ""

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install requests

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          DAMIAN_BOT_CHAT: ${{ secrets.DAMIAN_BOT_CHAT }}
          MESSAGE: ${{ github.event.inputs.MESSAGE || 'Ping desde GitHub Actions' }}
        run: python telegram_ping.py
